### ISSUE TITLE
Add link back to ESMO page

### ISSUE THREAD

**Issue by heikekonow** [digital-earths-global-hackathon/hamburg-node#5]
Add a link back to the ESMO page for the global hackathon. Link is: https://www.wcrp-esmo.org/activities/wcrp-global-km-scale-hackathon-2025
Should be mentioned in the first section (Welcome). 

Do we need a menu content section for the global hackathon as well? Or is one link in the first section sufficient?

**Comment by lkluft** [comment]
I would argue that a link to the first section is sufficient. I am not a big fan of external links in content menus.

**Comment by heikekonow** [comment]
closed with #7
